org.gradle.jvmargs=-Xmx256m -Xms128m -XX:MaxMetaspaceSize=128m
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configureondemand=true
android.useAndroidX=true
android.enableJetifier=true
android.lint.check=false
android.experimental.lint.missingBaselineIsNotEmpty=true
android.enableAapt2=true
android.aapt2FromMavenOverride=/data/data/com.termux/files/usr/bin/aapt2
